<?php

/**
 * SimplyREST
 *
 * Define your custom constants here
 *
 * @author Vince Urag
 */

define("SAMPLE_CONST", "This is a sample value.");

//DB users table
define("TABLE_USERS",           "users");
define("TABLE_USERS_USERID",    "username");
define("TABLE_USERS_PASSWORD",  "password");
define("TABLE_USERS_FIRSTNAME", "firstname");
define("TABLE_USERS_LASTNAME",  "lastname");
define("TABLE_USERS_EMAIL",     "email");
define("TABLE_USERS_PREMIUM",   "ispremium");
define("TABLE_USERS_SECRET_KEY_PASSWORD","SECRET_KEY_PASSWORD");
define("TABLE_USERS_SECRET_KEY_EMAIL","SECRET_KEY_EMAIL");
define("TABLE_USERS_SAMPLE",    "sample");
define("TABLE_USERS_SAMPLE2",   "sample2");

//DB votes table
define("TABLE_VOTES", 					"votes");
define("TABLE_VOTES_VOTE_ID", 			"VOTE_ID");
define("TABLE_VOTES_USERNAME", 			"USER_ID");
define("TABLE_VOTES_PLACE_ID", 			"PLACE_ID");
define("TABLE_VOTES_OVERALL_VOTE", 		"OVERALL_VOTE");
define("TABLE_VOTES_AMENITY_STAIRS", 	"AMENITY_STAIRS");
define("TABLE_VOTES_AMENITY_WALKWAYS", 	"AMENITY_WALKWAYS");
define("TABLE_VOTES_AMENITY_CORRIDORS", 	"AMENITY_CORRIDORS");
define("TABLE_VOTES_AMENITY_DOORS", 	"AMENITY_DOORS");
define("TABLE_VOTES_AMENITY_TOILETS", 	"AMENITY_TOILETS");
define("TABLE_VOTES_AMENITY_ELEVATORS", 	"AMENITY_ELEVATORS");
define("TABLE_VOTES_AMENITY_RAMPS", 	"AMENITY_RAMPS");
define("TABLE_VOTES_AMENITY_PARKING", 	"AMENITY_PARKING");
define("TABLE_VOTES_AMENITY_BUZZERS", 	"AMENITY_BUZZERS");
define("TABLE_VOTES_AMENITY_HANDRAILS", 	"AMENITY_HANDRAILS");
define("TABLE_VOTES_AMENITY_THRESHOLDS", 	"AMENITY_THRESHOLDS");
define("TABLE_VOTES_AMENITY_FLOOR", 	"AMENITY_FLOOR");
define("TABLE_VOTES_AMENITY_FOUNTAINS", 	"AMENITY_FOUNTAINS");
define("TABLE_VOTES_AMENITY_PHONES", 	"AMENITY_PHONES");
define("TABLE_VOTES_AMENITY_SEATING", 	"AMENITY_SEATING");

//DB places table
define("TABLE_PLACES", 					"places");
define("TABLE_PLACES_PLACE_ID", 		"PLACE_ID");
define("TABLE_PLACES_PLACE_NAME", 		"PLACE_NAME");
define("TABLE_PLACES_PLACE_ADDRESS", 		"PLACE_ADDRESS");
define("TABLE_PLACES_PLACE_CITY", 		"PLACE_CITY");
define("TABLE_PLACES_PLACE_TYPE", 		"PLACE_TYPE");
define("TABLE_PLACES_PLACE_SCORE_UPVOTE", 		"PLACE_SCORE_UPVOTE");
define("TABLE_PLACES_PLACE_SCORE_DOWNVOTE", 		"PLACE_SCORE_DOWNVOTE");
define("TABLE_PLACES_TOTAL_UPVOTES", 	"TOTAL_UPVOTES");
define("TABLE_PLACES_TOTAL_DOWNVOTES", 	"TOTAL_DOWNVOTES");

define("TABLE_PLACES_AMENITY_STAIRS", 	"AMENITY_STAIRS");
define("TABLE_PLACES_AMENITY_WALKWAYS", 	"AMENITY_WALKWAYS");
define("TABLE_PLACES_AMENITY_CORRIDORS", 	"AMENITY_CORRIDORS");
define("TABLE_PLACES_AMENITY_DOORS", 	"AMENITY_DOORS");
define("TABLE_PLACES_AMENITY_TOILETS", 	"AMENITY_TOILETS");
define("TABLE_PLACES_AMENITY_ELEVATORS", 	"AMENITY_ELEVATORS");
define("TABLE_PLACES_AMENITY_RAMPS", 	"AMENITY_RAMPS");
define("TABLE_PLACES_AMENITY_PARKING", 	"AMENITY_PARKING");
define("TABLE_PLACES_AMENITY_BUZZERS", 	"AMENITY_BUZZERS");
define("TABLE_PLACES_AMENITY_HANDRAILS", 	"AMENITY_HANDRAILS");
define("TABLE_PLACES_AMENITY_THRESHOLDS", 	"AMENITY_THRESHOLDS");
define("TABLE_PLACES_AMENITY_FLOOR", 	"AMENITY_FLOOR");
define("TABLE_PLACES_AMENITY_FOUNTAINS", 	"AMENITY_FOUNTAINS");
define("TABLE_PLACES_AMENITY_PHONES", 	"AMENITY_PHONES");
define("TABLE_PLACES_AMENITY_SEATING", 	"AMENITY_SEATING");